[package]
name = "wasabi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_winit_vulkano = { git = "https://github.com/Kaydax/egui_winit_vulkano.git" }
vulkano-shaders = { git = "https://github.com/Kaydax/vulkano.git" }
egui_demo_lib = "0.17.0"
vulkano-win = { git = "https://github.com/Kaydax/vulkano.git" }
egui-winit = "0.17.0"
bytemuck = "1.8.0"
vulkano = { git = "https://github.com/Kaydax/vulkano.git" }
kdmapi = { git = "https://github.com/arduano/kdmapi.git", rev = "9329cfc" }
egui = "0.17.0"
winit = "0.26"
image = "0.23.14"
ahash = "0.7.6"
cgmath = "0.18.0"
nalgebra-glm = "0.17.0"
rayon = "1.5.3"
midi-toolkit-rs = { git = "https://github.com/arduano/midi-toolkit-rs", rev = "f30ca8a" }
xsynth-core = { path = "../xsynth/core" }
xsynth-realtime = { path = "../xsynth/realtime" }
gen-iter = "0.2.1"
enum_dispatch = "0.3.8"
palette = "0.6.0"
crossbeam-channel = "0.5.5"
rand = "0.8.5"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
