[package]
name = "wasabi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_winit_vulkano = "0.20.0"
vulkano-shaders = "0.31.0"
egui_demo_lib = "0.19.0"
vulkano-win = "0.31.0"
vulkano-util = "0.31.0"
egui-winit = "0.19.0"
bytemuck = "1.8.0"
vulkano = "0.31.0"
kdmapi = { git = "https://github.com/arduano/kdmapi.git", rev = "9329cfc" }
egui = "0.19.0"
winit = "0.27.3"
rayon = "1.5.3"
midi-toolkit-rs = { git = "https://github.com/arduano/midi-toolkit-rs", rev = "907dec1" }
xsynth-core = { git = "https://github.com/arduano/xsynth.git", rev = "7875b93" }
xsynth-realtime = { git = "https://github.com/arduano/xsynth.git", rev = "7875b93" }
gen-iter = "0.2.1"
enum_dispatch = "0.3.8"
palette = "0.6.0"
crossbeam-channel = "0.5.5"
rand = "0.8.5"
confy = "0.5.0"
serde_derive = "1.0.145"
serde = "1.0.145"
toml = "0.5.9"
rfd = "0.10.0"
colors-transform = "0.2.11"
directories = "4.0.1"
rustc-hash = "1.1.0"
atomic_float = "0.1.0"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
