[package]
name = "wasabi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_winit_vulkano = "0.20.0"
vulkano-shaders = "0.31.0"
egui_demo_lib = "0.19.0"
vulkano-win = "0.31.0"
vulkano-util = "0.31.0"
egui-winit = "0.19.0"
bytemuck = "1.8.0"
vulkano = "0.31.0"
kdmapi = { git = "https://github.com/arduano/kdmapi.git", rev = "9329cfc" }
egui = "0.19.0"
winit = "0.27.3"
#image = "0.24.4"
#ahash = "0.8.0"
#cgmath = "0.18.0"
#nalgebra-glm = "0.17.0"
rayon = "1.5.3"
midi-toolkit-rs = { git = "https://github.com/arduano/midi-toolkit-rs", rev = "f30ca8a" }
#xsynth-core = { git = "https://github.com/arduano/xsynth.git", rev = "ff5e1a5" }
#xsynth-realtime = { git = "https://github.com/arduano/xsynth.git", rev = "ff5e1a5" }
xsynth-core = { path = "/mnt/jar/Projects/Rust/xsynth/core" }
xsynth-realtime = { path = "/mnt/jar/Projects/Rust/xsynth/realtime" }
gen-iter = "0.2.1"
enum_dispatch = "0.3.8"
palette = "0.6.0"
crossbeam-channel = "0.5.5"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
