[package]
name = "wasabi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_winit_vulkano = "0.22.0"
vulkano-shaders = "0.32.0"
vulkano-win = "0.32.0"
vulkano-util = "0.32.0"
egui-winit = "0.20.1"
bytemuck = "1.8.0"
vulkano = "0.32.3"
kdmapi = { git = "https://github.com/arduano/kdmapi.git" }
egui = "0.20.1"
winit = "0.27.3"
rayon = "1.5.3"
midi-toolkit-rs = { git = "https://github.com/arduano/midi-toolkit-rs" }
xsynth-core = { git = "https://github.com/arduano/xsynth.git" }
xsynth-realtime = { git = "https://github.com/arduano/xsynth.git" }
gen-iter = "0.3.0"
enum_dispatch = "0.3.8"
palette = "0.6.0"
crossbeam-channel = "0.5.5"
rand = "0.8.5"
confy = "0.5.1"
serde_derive = "1.0.145"
serde = "1.0.145"
toml = "0.6.0"
colors-transform = "0.2.11"
rustc-hash = "1.1.0"
atomic_float = "0.1.0"
egui_file = { git = "https://github.com/StratusFearMe21/egui_file.git" }
clap = "4.2.1"
panicui = "0.1.0"
thiserror = "1.0.40"
miette = { version = "5.7.0", features = ["fancy-no-backtrace"] }
crossterm = "0.26.1"
dirs = "5.0.0"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
lto = true
