[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get install software-properties-common; apt-get update; add-apt-repository ppa:deadsnakes/ppa; apt-get install -y python3.8 libgtk-3-dev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev",
]
