[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y python3 libgtk-3-dev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev",
]

# [target.x86_64-unknown-linux-musl]
# pre-build = [
#     "apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y python3 libgtk-3-dev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev",
# ]

# [target.arm-unknown-linux-gnueabi]
# pre-build = [
#     "apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y python3 libgtk-3-dev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev",
# ]

# [target.arm-unknown-linux-gnueabihf]
# pre-build = [
#     "apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y python3 libgtk-3-dev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev",
# ]

# [target.armv7-unknown-linux-gnueabihf]
# pre-build = [
#     "apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y python3 libgtk-3-dev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev",
# ]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64; apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y python3 libgtk-3-dev:arm64 libasound2-dev:arm64 portaudio19-dev:arm64 crossbuild-essential-arm64 libpulse-dev:arm64 libdbus-1-dev:arm64",
]

# [target.aarch64-unknown-linux-musl]
# pre-build = [
#     "apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y python3 libgtk-3-dev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev",
# ]
