[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y python3 libgtk-3-dev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev",
]
