on: [pull_request]

name: Lints

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Initialize Cargo
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
          cache-on-failure: true

      - uses: Swatinem/rust-cache@v2
        name: Cargo Cache

      - uses: actions-rs/cargo@v1
        name: Check code formatting
        with:
          command: fmt
          args: --all -- --check

      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install -y libgtk-3-dev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev

      - uses: actions-rs/cargo@v1
        name: Check code with clippy
        with:
          command: clippy
          args: --all -- --deny "warnings"
