name: Check Version Change

on:
  push:
    branches:
      - master

jobs:
  tag-new-versions:
    name: Tag new versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions-rs/toolchain@v1
        name: Initialize Cargo
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Get current version
        run: |
          cargo metadata --format-version 1 --no-deps | \
          jq ".packages[0].version" -r > \
          version.txt

      - name: Output version
        id: get-version
        run: |
          echo "version=v$(cat version.txt)" >> "$GITHUB_ENV"

      - uses: rickstaa/action-create-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets. PATNAME }}
        with:
          tag: ${{ env.version }}
          tag_exists_error: false
          message: "Release ${{ env.version }}"
