name: Check Version Change

on:
  push:
    branches:
      - master

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions-rs/toolchain@v1
        name: Initialize Cargo
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Get current version
        run: |
          cargo metadata --format-version 1 --no-deps | \
          jq ".packages[0].version" -r > \
          version.txt

      - name: Output version
        id: get-version
        run: |
          echo ::set-output name=version::v$(cat version.txt)

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.get-version.outputs.version }}
          tag_exists_error: false
          message: "Release ${{ steps.get-version.outputs.version }}"
